version: '3'

services:
  node-red:
    image: nodered/node-red-docker
    ports:
      - "1880:1880"
  
  db:
    image: influxdb:1.4-alpine
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin 
      - INFLUXDB_ADMIN_USER=supersecretpassword
      - INFLUXDB_DB=ttndb
      - INFLUXDB_USER=isen
      - INFLUXDB_USER_PASSWORD=Welkom#1
    ports:
      - "8086:8086"
  
  dashboard:
    image: grafana/grafana
    ports:
      - "4000:3000"